[tool.poetry]
name = 'medparse'
version = '0.0.1'
authors = ['Noam Finkelstein']
description = 'Automated information extraction from medical documents'

[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'
